---
version: '3.8'
services:
  vproapp:
    build:
      context: ./Docker-files/app/
    image: ritikgoel/vprofile-app
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
  vprodb:
    build:
      context: ./Docker-files/db/
    image: ritikgoel/vprofile-db
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
  vproweb:
    build:
      context: ./Docker-files/web/
    image: ritikgoel/vprofile-web
    container_name: vproweb
    ports:
      - "80:80"
     
  vprocache01:
    image: memcached
    container_name: vprocache01
    ports:
      - "11211:11211"
  vpromq01:
    image: rabbitmq
    container_name: vpromq01
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
volumes:
  vprodbdata: {}
  vproappdata: {}
