apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpromq
  template:
    metadata:
      labels:
        app: vpromq
    spec:
      containers:
        - name: vpromq
          image: rabbitmq
          ports:
            - name: mq-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rabbitmq_user_password
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
