---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprormq
  template:
    metadata:
      labels:
        app: vprormq
    spec:
      containers:
        - name: rmq-container
          image: rabbitmq
          ports:
            - name: rmq-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: secret-map
                  key: rabbitmq_pass
            - name: RABBITMQ_DEFAULT_USER
              value: guest

