---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpromc
  template:
    metadata:
      labels:
        app: vpromc
    spec:
      containers:
        - name: mc-container
          image: memcached
          ports:
            - name: mc-port
              containerPort: 11211
